name: Build and Push Docker Image

# Image Repository:
# https://hub.docker.com/repository/docker/fintechsalad/gateway-service

on:
  workflow_run:
    workflows:
      - Merge to Main Branch
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setting Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setting Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for github-action-get-previous-tag

      - name: Get Latest Tag
        id: get-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v1.0.0

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpnsl9i9glra7do93iv
          CR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ steps.get-tag.outputs.tag }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG -f ci/Dockerfile .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
